name: CI

on:
  push:
  # schedule:
  # - cron: 0 10-20 * * 1-5 # every hour in working hour of working day
  # - cron: 0 6 * * 1-5 # every working day 

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
         ref: master
    - name: Run update script
      run: make update git_setup autocommit
    - uses: ad-m/git-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
